on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run java checkstyle
  # You may pin to the exact commit or the version.
  # uses: nikitasavinov/checkstyle-action@79490c0fdcc3ab5dd2b50a0e82a5bfc4fe63f0a9
      uses: nikitasavinov/checkstyle-action@0.6.0
      with:
    #Checkstyle config file
          checkstyle_config: 2IP90_checks.xml      
